backend:
  name: github
  repo: joecasa1/broke-budget-site

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    folder: content/articles
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - label: "Featured Image"
    name: "topimage"
    widget: "image"
    default: "/assets/financial-peace.jpg"
