backend:
  name: github
  repo: joecasa1/broke-budget-site

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    folder: content/articles
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: "topimage", label: "Featured Image", widget: "image", required: false, default: "/assets/financial-peace.jpg" }
      - { name: body, label: Body, widget: markdown }
  - name: lessons
    label: Lessons
    folder: content/lessons
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: "topimage", label: "Featured Image", widget: "image", required: false, default: "/assets/financial-peace.jpg" }
      - { name: lessonnumber, label: "Lesson Number", widget: number }
      - { name: body, label: Body, widget: markdown }
